basic_settings:
  site_title: Rezak Souilah
  site_tagline: Matheamtics researcher.
  favicon_image: 
header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Posts'
      url: '/'
    - title: 'About'
      url: '/about'

social_settings:
  facebook_url: ''
  twitter_url: 'https://twitter.com/RezakSouilah'
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/lezaz'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""

